name: Compile high-light

on:
  push:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: high-light/high-light.scss
          destination: dist/high-light.css
          outputStyle: expanded

      # Auto commits minified content to the existing files
      - name: Auto commit build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Compiled css"
          branch: ${{ github.ref }}
